repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [pem]
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--sp, setup.cfg]
        types_or: [python]
        exclude: '^.*migrations.*$'
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        types: [python]
        exclude: .git,*/migrations/*,*/static/CACHE/*,docs,python_env,__pycache__,settings.py,manage.py
  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       types: [python]
  #       args: [--backend, setup.cfg]
