# Generated by Django 5.0.6 on 2024-07-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_last_changed", models.DateTimeField(auto_now=True)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-dt_created", "-dt_last_changed"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_last_changed", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="The message we sent.", null=True),
                ),
            ],
            options={
                "ordering": ["-dt_created", "-dt_last_changed"],
                "abstract": False,
            },
        ),
    ]
